# General scraper settings
base_url: "https://www.threads.net"
timeout: 15
use_offline: true         # default to offline for guaranteed run
use_proxies: false        # set true to use proxies from proxies.json
limit: 50
# Default usernames used if none provided via CLI
usernames:
  - zuck
  - mosseri
# Optional cookie (can also be set via .env as THREADS_COOKIE)
cookie: ""
